In [3]:
#hiddencell
from pbl_tools import *

# 스테이지 2

# 1.NumPy 라이브러리(Library) 불러오기
[문제 1]    
numpy 라이브러리를 불러오기 위해서 아래 빈칸을 채워 주세요.  
numpy는 자주 사용하는 라이브러리(Library)이므로 축약어인 np로 불러와 주세요.

In [3]:
import ___ as np

In [4]:
#checkcode
ensure_vals(globals(), 'np')
@check_safety
def check(user_answer_pandas=np):
    if hasattr(user_answer_pandas, 'array'):
        return True
    else:
        return False
check()

True

# 2.다양한 차원(dimension)의 NumPy 배열 생성하기

[문제 2]  
3개의 벡터를 만들어 봅시다. 조건은 아래와 같습니다.
- 1차원 벡터: 1로 구성되어 있음, shape: (3)
- 2차원 벡터: 0으로 구성되어 있음, shape: (2, 3)
- 3차원 벡터: 0으로 구성되어 있음, shape: ((2, 3, 2))

In [4]:
import numpy as np

one_dimension = np.ones(3)
print("---1차원 벡터---\n",one_dimension)

two_dimension = np.zeros((2,3))
print("\n---2차원 행렬---\n",two_dimension)

three_dimension = np.ones((2,3,2))
print("\n---3차원 텐서---\n",three_dimension)

---1차원 벡터---
 [1. 1. 1.]

---2차원 행렬---
 [[0. 0. 0.]
 [0. 0. 0.]]

---3차원 텐서---
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


True

In [ ]:
#checkcode
ensure_vals(globals(), 'one_dimension', 'two_dimension', 'three_dimension')
@check_safety
def check(
    one_dimension: np.array,
    two_dimension: np.array,
    three_dimension: np.array
):
    c_point1 = np.array_equal(one_dimension, np.ones(3))
    c_point2 = np.array_equal(two_dimension, np.zeros((2,3)))
    c_point3 = np.array_equal(three_dimension, np.ones((2,3,2)))

    if c_point1 and c_point2 and c_point3:
        return True
    else:
        return False

check(one_dimension, two_dimension, three_dimension)

# 3.1차원 배열(array) 생성하기

In [6]:
np.array([1,2,3])


array([1, 2, 3])

# 4.2차원 배열(array) 생성하기

In [7]:
np.array([[1,2,3],
          [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

# 5.3차원 배열(array) 생성하기

In [8]:
np.array([[[1,2],
           [3,4],
           [5,6]],
           [[7,8],
           [9,10],
           [11,12]]])

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# 6.2차원 배열(array) 생성하기 실습

[문제 2]  
NumPy의 `zeros()` 함수를 사용해서, 행이 2개이고 열이 3개인 
모든 요소가 **0으로 초기화된 행렬** 을 만들어보세요.         
아래 빈칸을 채워주세요.

In [9]:
np.zeros((___))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
#checkcode
ensure_vals(globals())
@check_safety
def check(user_answer=_):
    check0 = user_answer.shape == (2,3)
    check1 = 0 in user_answer
    
    if check0 and check1: 
        return True
    else:
        return False
check()

True

# 7.3차원 배열(array) 생성하기 실습

[문제 3]  
NumPy의 ones() 함수를 사용해서, 깊이 2개, 행이 3개, 열이 4개인 모든 요소가 **1로 초기화된 텐서** 를 만들어보세요.  
아래 빈칸을 채워주세요.

In [12]:
np.___((___))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [13]:
#checkcode
ensure_vals(globals())
@check_safety
def check(user_answer=_):
    check0 = user_answer.shape == (2,3,4)
    check1 = 1 in user_answer
    
    if check0 and check1: 
        return True
    else:
        return False
check()

True