In [2]:
#hiddencell
from pbl_tools import *

# 스테이지 6

# 1.NumPy 라이브러리(Library) 불러오기
[문제 1]    
numpy 라이브러리를 불러오기 위해서 아래 빈칸을 채워 주세요.    
numpy는 자주 사용하는 라이브러리이므로 축약어인 np로 불러와 주세요. 

In [4]:
#checkcode
ensure_vals(globals(), 'np')
@check_safety
def check(user_answer_pandas=np):
    if hasattr(user_answer_pandas, 'array'):
        return True
    else:
        return False
check()

True

# 2.누적 합(cumsum) 구하기

In [5]:
two_dimension = np.array([[5,10],
                          [15,20]])

np.cumsum(two_dimension)

array([ 5, 15, 30, 50])

# 3.NumPy 배열의 축(axis)을 기준으로 누적 합(cumsum) 구하기

In [13]:
two_dimension = np.array([[5,10],
                          [15,20]])

np.cumsum(two_dimension, axis = 1)

array([[ 5, 15],
       [15, 35]])

# 4.NumPy 배열의 축(axis)을 기준으로 누적 합(cumsum) 구하기 실습
[문제 2]  
two_dimension 배열에서 수직 방향으로 누적 합을 계산해 보세요.

In [10]:
two_dimension = np.array([[5,10],
                          [15,20]])

np.___(___, axis = ___)

array([[ 5, 10],
       [20, 30]])

In [11]:
#checkcode
ensure_vals(globals(),'two_dimension')
@check_safety
def check(user_answer=_):
    check1 = (user_answer == np.cumsum(two_dimension, axis = 0)).all()
    if check1:
        return True
    else:
        return False
check()

True

# 5.e의 지수함수(exp) 적용

In [16]:
np.exp(2)

7.38905609893065

# 6.e의 지수함수(exp) 적용 실습
[문제 3]   
[1,2,3,4] 리스트 배열에 대해 각 요소에 대한 지수 값을 계산해보세요.  
아래 빈칸을 채워보세요.

In [16]:
np.___(___)   

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [17]:
#checkcode
ensure_vals(globals())
@check_safety
def check(user_answer=_):
    check1 = (user_answer == np.exp([1,2,3,4])).all()
    if check1:
        return True
    else:
        return False
check()

True

# 7.NumPy 배열의 제곱근(sqrt) 계산하기

In [18]:
np.sqrt(4)

2.0

# 8.NumPy 배열의 제곱근(sqrt) 계산하기 실습

[문제 4]  
4,9,16을 리스트 형태로 삽입하여 제곱근을 출력해보세요.

In [19]:
np.___(___)

array([2., 3., 4.])

In [20]:
#checkcode
ensure_vals(globals())
@check_safety
def check(user_answer=_):
    check1 = (user_answer == np.sqrt([4,9,16])).all()
    if check1:
        return True
    else:
        return False
check()

True