In [ ]:
#hiddencell
from pbl_tools import *

# 스테이지 5

# 1.NumPy 라이브러리(Library) 불러오기
[문제 1]    
numpy 라이브러리를 불러오기 위해서 아래 빈칸을 채워 주세요.    
numpy는 자주 사용하는 라이브러리이므로 축약어인 np로 불러와 주세요. 

In [ ]:
___ numpy ___ np

In [ ]:
#checkcode
ensure_vals(globals(), 'np')
@check_safety
def check(user_answer_pandas=np):
    if hasattr(user_answer_pandas, 'array'):
        return True
    else:
        return False
check()

True

# 2.2차원 배열(array) 생성하기

In [ ]:
twelve_array = np.array([[3,4,5,4],
                         [1,5,6,7],
                         [9,2,6,4]])

twelve_array

array([[3, 4, 5, 4],
       [1, 5, 6, 7],
       [9, 2, 6, 4]])

# 3.NumPy 배열(array)에서 최댓값(max) 찾기

[문제 2]  
`numpy`를 사용하여 배열 `twelve_array`에서 최대값을 찾는 과정입니다. 

- `numpy` 라이브러리가 이미 임포트되어 있다고 가정하고, `np.max()` 함수를 사용하여 배열 `twelve_array`의 최대값을 찾습니다.


In [ ]:
np.___(twelve_array)

9

In [ ]:
#checkcode
ensure_vals(globals(),'twelve_array')
@check_safety
def check(user_answer=_):
    if (user_answer==np.max(twelve_array)):
        return True
    else:
        return False
check()

# 4.NumPy 배열(array)에서 최솟값(min) 찾기

[문제 3]  
twelve_array 배열에서 가장 작은 값을 반환해보세요.  
아래 빈칸을 채워보세요.

In [ ]:
___.___(___)

1

In [ ]:
#checkcode
ensure_vals(globals(),'twelve_array')
@check_safety
def check(user_answer=_):
    if (user_answer==np.min(twelve_array)):
        return True
    else:
        return False
check()

False

# 5.NumPy 배열의 축(axis)을 기준으로 최댓값 구하기

[문제 4]  

 `numpy`를 사용하여 배열 `twelve_array`의 각 열에서 최대값을 찾는 과정입니다. 

- `numpy` 라이브러리가 이미 임포트되어 있다고 가정하고, `np.max()` 함수를 사용하여 배열 `twelve_array`의 각 열에 대한 최대값을 찾습니다. `axis=0` 매개변수를 사용하여 열 별로 연산을 지정합니다.

In [ ]:
np.___(twelve_array, ___ = 0)

array([9, 5, 6, 7])

In [ ]:
#checkcode
ensure_vals(globals(),'twelve_array')
@check_safety
def check(user_answer):
    
    check_user = np.max(twelve_array, axis = 0)
    check1 = (check_user == user_answer).all
    
    if check1:
        return True
    else:
        return False
check(_)

# 6.NumPy 배열의 축(axis)을 기준으로 최솟값(min) 구하기

[문제 5]  
`numpy`를 사용하여 2차원 배열 `twelve_array`의 각 행에서 최소값을 찾는 과정입니다. 

- `numpy` 라이브러리가 이미 임포트되어 있다고 가정하고, `np.min()` 함수를 사용하여 배열 `twelve_array`의 각 행에 대한 최소값을 찾습니다. `axis=1` 매개변수를 사용하여 행 별로 연산을 지정합니다.

In [ ]:
...

array([3, 1, 2])

In [ ]:
#checkcode
ensure_vals(globals(),'twelve_array')
@check_safety
def check(user_answer=_):
    check1 = 3 in _
    check2 = 1 in _
    check3 = 2 in _
    if check1 and check2 and check3:
        return True
    else:
        return False
check()

True

# 7.NumPy 배열의 전체 원소 합(sum) 구하기

[문제 6]  
`numpy`를 사용하여 배열 `twelve_array`의 모든 요소의 합을 계산하는 과정입니다.

- `numpy` 라이브러리가 이미 임포트되어 있다고 가정하고, `np.sum()` 함수를 사용하여 배열 `twelve_array`의 전체 요소의 합을 계산합니다.

In [ ]:
___.___(twelve_array)

56

In [ ]:
#checkcode
ensure_vals(globals(),'twelve_array')
@check_safety
def check(user_answer):
    
    check_user = np.sum(twelve_array)
    check1 = (check_user == user_answer).all
    
    if check1:
        return True
    else:
        return False
check(_)

# 8.NumPy 배열의 각 수평 방향의 합(sum) 구하기
[문제 7]  
twelve_array 에서 각 수평 방향의 합계를 구해보세요.  
아래 빈칸을 채워보세요.

In [ ]:
np.___(___, axis = ___)

array([16, 19, 21])

In [ ]:
#checkcode
ensure_vals(globals(),'twelve_array')
@check_safety
def check(user_answer=_):
    if (user_answer==np.sum(twelve_array, axis =1)).all():
        return True
    else:
        return False
check()

True