In [1]:
#hiddencell
from pbl_tools import *

# 스테이지 4

# 1.NumPy 라이브러리(Library) 불러오기
[문제 1]    
numpy 라이브러리를 불러오기 위해서 아래 빈칸을 채워 주세요.    
numpy는 자주 사용하는 라이브러리이므로 축약어인 np로 불러와 주세요. 

In [2]:
___ numpy ___ np

In [3]:
#checkcode
ensure_vals(globals(), 'np')
@check_safety
def check(user_answer_pandas=np):
    if hasattr(user_answer_pandas, 'array'):
        return True
    else:
        return False
check()

True

# 2.1차원 배열(array) 생성하기

In [4]:
jump_num = np.array([1,2,3,4])
same_num = np.array([2,2,2,2])

# 3.NumPy 배열(array)간 덧셈(+) 연산하기

[문제 2]  
두 변수 `jump_num`과 `same_num`의 값을 더하는 과정입니다. 주어진 코드를 완성하여 두 변수의 합을 계산하세요.

1. 두 변수 `jump_num`과 `same_num`이 각각 정의되어 있다고 가정합니다.
2. 두 변수를 더하는 연산을 수행합니다. 

In [6]:
jump_num ___ same_num

array([3, 4, 5, 6])

In [ ]:
#checkcode
ensure_vals(globals())
@check_safety
def check(user_answer_pandas):
    
    jump_num = np.array([1,2,3,4])
    same_num = np.array([2,2,2,2])
    
    check_me = jump_num + same_num
    check1 = (check_me == user_answer_pandas).all
    
    if check1:
        return True
    else:
        return False
check(_)

# 4.NumPy 배열(array)간 뺄셈(-) 연산하기
[문제 3]  
두 변수 `jump_num`과 `same_num`의 값을 빼는 과정입니다. 주어진 코드를 완성하여 두 변수의 차이를 계산하세요.

1. 두 변수 `jump_num`과 `same_num`이 각각 정의되어 있다고 가정합니다.
2. 두 변수를 빼는 연산을 수행합니다. 

In [8]:
jump_num ___ same_num

array([-1,  0,  1,  2])

In [ ]:
#checkcode
ensure_vals(globals())
@check_safety
def check(user_answer_pandas):
    
    jump_num = np.array([1,2,3,4])
    same_num = np.array([2,2,2,2])
    
    check_me = jump_num - same_num
    check1 = (check_me == user_answer_pandas).all
    
    if check1:
        return True
    else:
        return False
check(_)

# 5.NumPy 배열(array)간 곱셈(*) 연산하기

[문제 4]  
두 변수 `jump_num`과 `same_num`을 곱하는 과정입니다. 주어진 코드를 완성하여 두 변수의 곱을 계산하세요.

1. 두 변수 `jump_num`과 `same_num`이 각각 정의되어 있다고 가정합니다.
2. 두 변수를 곱하는 연산을 수행합니다. 

In [10]:
jump_num ___ same_num

array([2, 4, 6, 8])

In [ ]:
#checkcode
ensure_vals(globals())
@check_safety
def check(user_answer_pandas):
    
    jump_num = np.array([1,2,3,4])
    same_num = np.array([2,2,2,2])
    
    check_me = jump_num * same_num
    check1 = (check_me == user_answer_pandas).all
    
    if check1:
        return True
    else:
        return False
check(_)

# 6.NumPy 배열(array)간 거듭제곱(**) 연산하기

[문제 5]    
변수 `jump_num`을 `same_num`으로 거듭제곱하는 과정입니다. 주어진 코드를 완성하여 거듭제곱 연산을 수행하세요.

1. 두 변수 `jump_num`과 `same_num`이 각각 정의되어 있다고 가정합니다.
2. `jump_num`을 `same_num`의 거듭제곱으로 계산합니다. 

In [12]:
jump_num ___ same_num

array([ 1,  4,  9, 16])

In [ ]:
#checkcode
ensure_vals(globals())
@check_safety
def check(user_answer_pandas):
    
    jump_num = np.array([1,2,3,4])
    same_num = np.array([2,2,2,2])
    
    check_me = jump_num ** same_num
    check1 = (check_me == user_answer_pandas).all
    
    if check1:
        return True
    else:
        return False
check(_)

# 7.NumPy 배열(array)간 나눗셈(/) 연산하기

[문제 6]  
변수 `jump_num`을 `same_num`으로 나누는 과정입니다. 주어진 코드를 완성하여 나눗셈 연산을 수행하세요.

1. 두 변수 `jump_num`과 `same_num`이 각각 정의되어 있다고 가정합니다.
2. `jump_num`을 `same_num`으로 나누는 연산을 수행합니다.

In [14]:
jump_num ___ same_num

array([0.5, 1. , 1.5, 2. ])

In [ ]:
#checkcode
ensure_vals(globals())
@check_safety
def check(user_answer_pandas):
    
    jump_num = np.array([1,2,3,4])
    same_num = np.array([2,2,2,2])
    
    check_me = jump_num / same_num
    check1 = (check_me == user_answer_pandas).all
    
    if check1:
        return True
    else:
        return False
check(_)

# 8.NumPy 배열간 비교(<) 연산하기


In [16]:
random_num = np.array([2,5,4,6]) 
same_three_num = np.array([3,3,3,3]) 

random_num < same_three_num 

array([ True, False, False, False])

# 9.2차원 배열(array) 생성하기

In [18]:
two_jump_num = np.array([[4,6],
                         [12,10]])
two_same_num = np.array([[2,2],
                         [2,2]])

# 10.2차원 배열(array) 연산 실습(1)

[문제 7]  
위에서 생성한 two_jump_num 과 two_same_num을 곱한 후 two_jump_num을 더해보세요.
그 값을 a 변수에 할당해 주세요.

In [20]:
a = ...
a

array([[12, 18],
       [36, 30]])

In [21]:
#checkcode
ensure_vals(globals(),'a')
@check_safety
def check(user_answer=a):
    if (user_answer[0] == [12, 18]).all():
        return True
    else:
        return False
check()

True

# 11.2차원 배열(array) 연산 실습(2)

[문제 8]  
위에서 생성한 two_jump_num와 two_same_num 을 나눈 후 two_jump_num을 곱해보세요.

In [22]:
...

array([[ 8., 18.],
       [72., 50.]])

In [34]:
#checkcode
ensure_vals(globals(),'two_jump_num','two_same_num')
@check_safety
def check(user_answer=_):
    if (user_answer==two_jump_num / two_same_num * two_jump_num).all():
        return True
    else:
        return False
check()

True

# 12.2차원 배열(array) 연산 실습(3)

[문제 9]  
`>` 왼쪽에는 two_same_num에 two_jump_num을 거듭제곱한 값을,   
`>` 오른쪽에는 two_jump_num 과 two_same_num을 곱한 값을 채워주세요.  

아래의 빈칸을 채워주세요.

In [24]:
___ > ___

array([[ True,  True],
       [ True,  True]])

In [25]:
#checkcode
ensure_vals(globals(),'two_same_num','two_jump_num')
@check_safety
def check(user_answer=_):
    if (sum(_) == ([2, 2])).all():
        return True
    else:
        return False
check()

True